$axure.loadCurrentPage({
  "url":"成长记录界面.html",
  "generationDate":new Date(1426661053949.62),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"value"],
  "page":{
    "packageId":"6faf9c93d38f49149a54b93eeae76c39",
    "type":"Axure:Page",
    "name":"成长记录界面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4d41da32b319455dae7db058f0eb0839",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":569}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcaf5b795308440badeeb1628862979b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":569}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息显示界面/u0.png"}},
{
          "id":"4d05b6231d404ffc9103348e067836a3",
          "label":"成长记录首页",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":72},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"0a7e5203f93f4f2cb414aec69e3b081c",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"7f93741887994f718838687bba603bbb",
                  "label":"",
                  "parentDynamicPanel":"4d05b6231d404ffc9103348e067836a3",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":187},
                    "size":{
                      "width":50,
                      "height":48},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"44"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"02484748acb546699c7e8579fab5ffa7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4d05b6231d404ffc9103348e067836a3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":187},
                        "size":{
                          "width":50,
                          "height":48},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"44"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/成长记录界面/u3.png"}},
{
                  "id":"fb23de988ad142c48a16ae574b9e86dc",
                  "label":"",
                  "parentDynamicPanel":"4d05b6231d404ffc9103348e067836a3",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "location":{
                      "x":70,
                      "y":197},
                    "size":{
                      "width":41,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0635761146964e9fa6c63d3b20481ce2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4d05b6231d404ffc9103348e067836a3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "location":{
                          "x":70,
                          "y":197},
                        "size":{
                          "width":41,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ba207fbbf0f04303bffdb4a93f85124a",
                  "label":"",
                  "parentDynamicPanel":"4d05b6231d404ffc9103348e067836a3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":0,
                      "y":235},
                    "size":{
                      "width":280,
                      "height":51},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"734ec7064fab45e8bd26864464d34464",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4d05b6231d404ffc9103348e067836a3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":0,
                          "y":235},
                        "size":{
                          "width":280,
                          "height":51},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 成长记录显示 to 成长相册",
                              "panelsToStates":[{
                                  "panelPath":["724668ab7b0d41a78fe89eba68963368"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]},
{
                              "action":"moveWidget",
                              "description":"移动 成长记录首页 到 (-300,72) 线性 100ms",
                              "objectsToMoves":[{
                                  "objectPath":["4d05b6231d404ffc9103348e067836a3"],
                                  "moveInfo":{
                                    "moveType":"location",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"-300",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"72",
                                      "stos":[]},
                                    "options":{
                                      "easing":"linear",
                                      "duration":100}}}]},
{
                              "action":"moveWidget",
                              "description":"移动 成长记录显示 到 (0,72) 线性 100ms",
                              "objectsToMoves":[{
                                  "objectPath":["724668ab7b0d41a78fe89eba68963368"],
                                  "moveInfo":{
                                    "moveType":"location",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"72",
                                      "stos":[]},
                                    "options":{
                                      "easing":"linear",
                                      "duration":100}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/成长记录界面/u7.png"}},
{
                  "id":"ee777f6203484c5095d71bc8ee71fd25",
                  "label":"",
                  "parentDynamicPanel":"4d05b6231d404ffc9103348e067836a3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":0,
                      "y":296},
                    "size":{
                      "width":280,
                      "height":51},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"10368720610941e9abe62dce1e5db0b1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4d05b6231d404ffc9103348e067836a3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":0,
                          "y":296},
                        "size":{
                          "width":280,
                          "height":51},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 成长记录显示 to 闪亮时刻",
                              "panelsToStates":[{
                                  "panelPath":["724668ab7b0d41a78fe89eba68963368"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]},
{
                              "action":"moveWidget",
                              "description":"移动 成长记录首页 到 (-300,72) 线性 100ms",
                              "objectsToMoves":[{
                                  "objectPath":["4d05b6231d404ffc9103348e067836a3"],
                                  "moveInfo":{
                                    "moveType":"location",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"-300",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"72",
                                      "stos":[]},
                                    "options":{
                                      "easing":"linear",
                                      "duration":100}}}]},
{
                              "action":"moveWidget",
                              "description":"移动 成长记录显示 到 (0,72) 线性 100ms",
                              "objectsToMoves":[{
                                  "objectPath":["724668ab7b0d41a78fe89eba68963368"],
                                  "moveInfo":{
                                    "moveType":"location",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"72",
                                      "stos":[]},
                                    "options":{
                                      "easing":"linear",
                                      "duration":100}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/成长记录界面/u7.png"}},
{
                  "id":"bfb9671209b34e50a41fec7d664332fd",
                  "label":"",
                  "parentDynamicPanel":"4d05b6231d404ffc9103348e067836a3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":0,
                      "y":357},
                    "size":{
                      "width":280,
                      "height":51},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"54acbe81952d48839c2a66f08586063f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4d05b6231d404ffc9103348e067836a3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":0,
                          "y":357},
                        "size":{
                          "width":280,
                          "height":51},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 成长记录显示 to 请假记录",
                              "panelsToStates":[{
                                  "panelPath":["724668ab7b0d41a78fe89eba68963368"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":3,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]},
{
                              "action":"moveWidget",
                              "description":"移动 成长记录首页 到 (-300,72) 线性 100ms",
                              "objectsToMoves":[{
                                  "objectPath":["4d05b6231d404ffc9103348e067836a3"],
                                  "moveInfo":{
                                    "moveType":"location",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"-300",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"72",
                                      "stos":[]},
                                    "options":{
                                      "easing":"linear",
                                      "duration":100}}}]},
{
                              "action":"moveWidget",
                              "description":"移动 成长记录显示 到 (0,72) 线性 100ms",
                              "objectsToMoves":[{
                                  "objectPath":["724668ab7b0d41a78fe89eba68963368"],
                                  "moveInfo":{
                                    "moveType":"location",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"72",
                                      "stos":[]},
                                    "options":{
                                      "easing":"linear",
                                      "duration":100}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/成长记录界面/u7.png"}},
{
                  "id":"f43b0981396b4d7290e1778f82bc2099",
                  "label":"",
                  "parentDynamicPanel":"4d05b6231d404ffc9103348e067836a3",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":280,
                      "height":172}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6f4a89a9ac7c44a383697014a616feb4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4d05b6231d404ffc9103348e067836a3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":280,
                          "height":172}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/成长记录界面/u13.png"}}]}]},
{
          "id":"724668ab7b0d41a78fe89eba68963368",
          "label":"成长记录显示",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":72},
            "size":{
              "width":320,
              "height":808}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onDrag":{
              "description":"OnDrag",
              "cases":[{
                  "description":"用例 1<br> (If &quot;[[this.x]]&quot; 等于 &quot;0&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"stringLiteral",
                      "value":"[[this.x]]",
                      "stos":[{
                          "computedType":"int",
                          "sto":"propCall",
                          "thisSTO":{
                            "sto":"var",
                            "name":"this"},
                          "prop":"x"}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"0",
                      "stos":[]}},
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 成长记录显示 y 轴拖动",
                      "objectsToMoves":[{
                          "objectPath":["724668ab7b0d41a78fe89eba68963368"],
                          "moveInfo":{
                            "moveType":"dragY",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]}]},
            "onDragDrop":{
              "description":"OnDragDrop",
              "cases":[{
                  "description":"用例 1<br> (If &quot;[[this.y]]&quot; &gt; &quot;72&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":">",
                    "leftExpr":{
                      "exprType":"stringLiteral",
                      "value":"[[this.y]]",
                      "stos":[{
                          "computedType":"int",
                          "sto":"propCall",
                          "thisSTO":{
                            "sto":"var",
                            "name":"this"},
                          "prop":"y"}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"72",
                      "stos":[]}},
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 成长记录显示 到 (0,72) 线性 300ms",
                      "objectsToMoves":[{
                          "objectPath":["724668ab7b0d41a78fe89eba68963368"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"72",
                              "stos":[]},
                            "options":{
                              "easing":"linear",
                              "duration":300}}}]}]},
{
                  "description":"用例 2<br> (Else If &quot;[[this.y]]&quot; &lt; &quot;-400&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"<",
                    "leftExpr":{
                      "exprType":"stringLiteral",
                      "value":"[[this.y]]",
                      "stos":[{
                          "computedType":"int",
                          "sto":"propCall",
                          "thisSTO":{
                            "sto":"var",
                            "name":"this"},
                          "prop":"y"}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"-400",
                      "stos":[]}},
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 成长记录显示 到 (0,-400) 线性 300ms",
                      "objectsToMoves":[{
                          "objectPath":["724668ab7b0d41a78fe89eba68963368"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"-400",
                              "stos":[]},
                            "options":{
                              "easing":"linear",
                              "duration":300}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"b5080b711f654fcb804eb3aeefd1dcb8",
              "label":"成长相册",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"746742b835494555b9cae80a369e32b2",
                  "label":"",
                  "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":30},
                    "size":{
                      "width":120,
                      "height":113},
                    "rotation":"354",
                    "textRotation":"354"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0e494d1b216e451796a0b857e2bbd542",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":30},
                        "size":{
                          "width":120,
                          "height":113},
                        "rotation":"354",
                        "textRotation":"354"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/成长记录界面/u16.png"}},
{
                  "id":"b6c3d4b7261e45e4a382f825479ba713",
                  "label":"",
                  "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":168,
                      "y":66},
                    "size":{
                      "width":65,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a5a8b93e36914d0d906c4ddd200fb18b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":168,
                          "y":66},
                        "size":{
                          "width":65,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0da37ab9f68041f7ac1e584604d12e33",
                  "label":"",
                  "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":146,
                      "y":92},
                    "size":{
                      "width":127,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"64c47a347f1d49c28a1e933d25fec069",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":146,
                          "y":92},
                        "size":{
                          "width":127,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d85ab60f70314629ae3ffaf7f6ef7169",
                  "label":"",
                  "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":32,
                      "y":210},
                    "size":{
                      "width":65,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dff25ed76108456498ba474261d723b0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":32,
                          "y":210},
                        "size":{
                          "width":65,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e36d830ac4e944a2ae4a3f62e18e79a5",
                  "label":"",
                  "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":10,
                      "y":236},
                    "size":{
                      "width":138,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"421a30db54af4f91b3c80d1d81418556",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":10,
                          "y":236},
                        "size":{
                          "width":138,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b6dc205f5f4a477f9ad22d0c99d2d5d3",
                  "label":"",
                  "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":175.380737304688,
                      "y":160.937103271484},
                    "size":{
                      "width":104,
                      "height":148},
                    "rotation":"15",
                    "textRotation":"15"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d724531afbbf48999847fe497fcc197b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":175.380737304688,
                          "y":160.937103271484},
                        "size":{
                          "width":104,
                          "height":148},
                        "rotation":"15",
                        "textRotation":"15"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/成长记录界面/u26.png"}},
{
                  "id":"845b632938264218a65bf638ff493b42",
                  "label":"",
                  "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":205,
                      "y":378},
                    "size":{
                      "width":65,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"afb94abbfa1a4e7b88265a3b05a0aa4f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":205,
                          "y":378},
                        "size":{
                          "width":65,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2d5b812ca0cb42059e78f94dbe2067e8",
                  "label":"",
                  "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":183,
                      "y":404},
                    "size":{
                      "width":113,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f70d362e6fc2485db75bc27181d0034a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":183,
                          "y":404},
                        "size":{
                          "width":113,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7f1979a72a32434699cd6c5d1b4bbb7a",
                  "label":"",
                  "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":14,
                      "y":350},
                    "size":{
                      "width":141,
                      "height":100},
                    "rotation":"352",
                    "textRotation":"352"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4cb60145e9af4a7c9d20d13dfbf7eb18",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":14,
                          "y":350},
                        "size":{
                          "width":141,
                          "height":100},
                        "rotation":"352",
                        "textRotation":"352"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/成长记录界面/u32.png"}},
{
                  "id":"9a38dd0dbd654ab2887842f8d2606ffa",
                  "label":"",
                  "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":44,
                      "y":518},
                    "size":{
                      "width":65,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"53030e409e734c2aa536412bc9f0be21",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":44,
                          "y":518},
                        "size":{
                          "width":65,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0634211cf01640ee9d30a023030d4511",
                  "label":"",
                  "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":22,
                      "y":544},
                    "size":{
                      "width":141,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e1667c0d37e94f7eae650bfa90ac7bb9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":22,
                          "y":544},
                        "size":{
                          "width":141,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1229505a58eb4cedbb0cf0457062c1ba",
                  "label":"",
                  "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":184.5,
                      "y":475.5},
                    "size":{
                      "width":110,
                      "height":153},
                    "rotation":"15",
                    "textRotation":"15"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"68d754eb5d054556a86ecb36b5563a59",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":184.5,
                          "y":475.5},
                        "size":{
                          "width":110,
                          "height":153},
                        "rotation":"15",
                        "textRotation":"15"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/成长记录界面/u38.png"}},
{
                  "id":"9a54c15f4b424c9da1c4a3d5d53c2349",
                  "label":"",
                  "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                  "type":"verticalLine",
                  "styleType":"verticalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":140,
                      "y":100},
                    "size":{
                      "width":10,
                      "height":117},
                    "rotation":"45",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/成长记录界面/u40_line.png"}},
{
                  "id":"df803256621e40a1a708ae4902e313d4",
                  "label":"",
                  "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                  "type":"verticalLine",
                  "styleType":"verticalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":159.901275634766,
                      "y":416.401275634766},
                    "size":{
                      "width":10,
                      "height":117},
                    "rotation":"45",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/成长记录界面/u40_line.png"}},
{
                  "id":"3f17abb4bce647e58a4d48e4f094aafd",
                  "label":"",
                  "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                  "type":"verticalLine",
                  "styleType":"verticalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":150.098724365234,
                      "y":266.401275634766},
                    "size":{
                      "width":10,
                      "height":117},
                    "rotation":"315",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/成长记录界面/u40_line.png"}}]},
{
              "id":"007366668fef413b80066473eb44dcce",
              "label":"闪亮时刻",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"a16b1a5357b5435a9e84b131d184dfcb",
                  "label":"",
                  "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":128,
                      "y":40},
                    "size":{
                      "width":172,
                      "height":170}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e7d1831bc07b444c9d635e4602402858",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":128,
                          "y":40},
                        "size":{
                          "width":172,
                          "height":170}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/成长记录界面/u43.png"}},
{
                  "id":"9dd01143a6544949adcc19ac17830f0f",
                  "label":"",
                  "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000099,
                      "opacity":1},
                    "location":{
                      "x":28,
                      "y":90},
                    "size":{
                      "width":72,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2648191a1b294952b94ba879a53d9740",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000099,
                          "opacity":1},
                        "location":{
                          "x":28,
                          "y":90},
                        "size":{
                          "width":72,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2a9824f1376b42bfa7b2fcf21dd01687",
                  "label":"",
                  "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "location":{
                      "x":15,
                      "y":119},
                    "size":{
                      "width":98,
                      "height":38}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8d3fd0c95db54a10bbf60cfb52ac1bf1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "location":{
                          "x":15,
                          "y":119},
                        "size":{
                          "width":98,
                          "height":38}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2c13e07174664ea491ff65c249250f3d",
                  "label":"",
                  "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":128,
                      "y":280},
                    "size":{
                      "width":172,
                      "height":170}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f9e3667bf7fe4c19b02da807a9561497",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":128,
                          "y":280},
                        "size":{
                          "width":172,
                          "height":170}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/成长记录界面/u43.png"}},
{
                  "id":"f1bcd706320048c4904b68b7c60d6aa4",
                  "label":"",
                  "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000099,
                      "opacity":1},
                    "location":{
                      "x":28,
                      "y":330},
                    "size":{
                      "width":72,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b06ab4b389b546559d8936efbc67123d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000099,
                          "opacity":1},
                        "location":{
                          "x":28,
                          "y":330},
                        "size":{
                          "width":72,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5a2f7f7364d94846856be36646f40975",
                  "label":"",
                  "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "location":{
                      "x":15,
                      "y":359},
                    "size":{
                      "width":98,
                      "height":38}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"557771df579044c095b53ec76fe34569",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "location":{
                          "x":15,
                          "y":359},
                        "size":{
                          "width":98,
                          "height":38}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"73455d8375584d6bac1cab4ca8a93909",
                  "label":"",
                  "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":128,
                      "y":510},
                    "size":{
                      "width":172,
                      "height":170}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"533df41d988d4164a2911fb8e5320fad",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":128,
                          "y":510},
                        "size":{
                          "width":172,
                          "height":170}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/成长记录界面/u43.png"}},
{
                  "id":"ab5f4c86c45d451ea9b4622094445e23",
                  "label":"",
                  "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000099,
                      "opacity":1},
                    "location":{
                      "x":28,
                      "y":560},
                    "size":{
                      "width":72,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"de6164f0d1714bccae1009d1ab35b414",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000099,
                          "opacity":1},
                        "location":{
                          "x":28,
                          "y":560},
                        "size":{
                          "width":72,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"54f4ac1bc1ba499891d007049b27857a",
                  "label":"",
                  "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "location":{
                      "x":15,
                      "y":589},
                    "size":{
                      "width":98,
                      "height":38}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d569acc732394cb9a5831e6d6430a0c6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "location":{
                          "x":15,
                          "y":589},
                        "size":{
                          "width":98,
                          "height":38}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"faffee6a7e7e4e9d8a79d2e3549993ee",
              "label":"请假记录",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"a98c0167e9e14505a95dd52fe83d737a",
                  "label":"",
                  "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "location":{
                      "x":84,
                      "y":50},
                    "size":{
                      "width":152,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bc3fd3696dd74d5fbd3ac8b6629d5781",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "location":{
                          "x":84,
                          "y":50},
                        "size":{
                          "width":152,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"292f8d1fec6f474e8faff0ca4842782e",
                  "label":"",
                  "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":290},
                    "size":{
                      "width":280,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x873333FF}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/成长记录界面/u63_line.png"}},
{
                  "id":"e449a0a6a3ec494b9dd6ad1d568dcea3",
                  "label":"",
                  "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":310},
                    "size":{
                      "width":280,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x873333FF},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a0c2175c70e748e1866475e6bdf3e254",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":310},
                        "size":{
                          "width":280,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x873333FF},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/成长记录界面/u64.png"}},
{
                  "id":"4ee29671ca84488883155a1cae394cd9",
                  "label":"",
                  "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":370},
                    "size":{
                      "width":280,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x873333FF},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c0430f0bbca345bbb6ce3f1e476f5a61",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":370},
                        "size":{
                          "width":280,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x873333FF},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/成长记录界面/u64.png"}},
{
                  "id":"615d2720ca094d338463cd97d5213e6e",
                  "label":"",
                  "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":68.5,
                      "y":94},
                    "size":{
                      "width":183,
                      "height":176}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a654ce4ec20a4c2ea36ee4b01540c8a1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":68.5,
                          "y":94},
                        "size":{
                          "width":183,
                          "height":176}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/成长记录界面/u68.png"}},
{
                  "id":"0ecf31d5bf8942d7a7ecb4f54960f98d",
                  "label":"",
                  "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x7A99FFFF},
                    "location":{
                      "x":190,
                      "y":154},
                    "size":{
                      "width":20,
                      "height":20},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF00}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b54d24a852de4748b46be37a58618d74",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x7A99FFFF},
                        "location":{
                          "x":190,
                          "y":154},
                        "size":{
                          "width":20,
                          "height":20},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF00}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/成长记录界面/u70.png"}},
{
                  "id":"dbdb862748de45f68d004a3680425ea8",
                  "label":"",
                  "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x7A99FFFF},
                    "location":{
                      "x":150,
                      "y":172},
                    "size":{
                      "width":20,
                      "height":20},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF00}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0747ce09b3f945d5a219f23ea4606a34",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x7A99FFFF},
                        "location":{
                          "x":150,
                          "y":172},
                        "size":{
                          "width":20,
                          "height":20},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF00}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/成长记录界面/u70.png"}},
{
                  "id":"5a9a219d5cff45389f0b81b74e71a304",
                  "label":"",
                  "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x7A99FFFF},
                    "location":{
                      "x":110,
                      "y":190},
                    "size":{
                      "width":20,
                      "height":20},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF00}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7c356060ea294eeeb6fae6edf0e22968",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"724668ab7b0d41a78fe89eba68963368",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x7A99FFFF},
                        "location":{
                          "x":110,
                          "y":190},
                        "size":{
                          "width":20,
                          "height":20},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF00}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/成长记录界面/u70.png"}}]}]},
{
          "id":"a36f97e992f74076a69282e6c8626cf6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0x7F3300CC},
            "location":{
              "x":3,
              "y":450},
            "size":{
              "width":40,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"45"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f98eeda7eb44bae8a74d83895ab1c84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0x7F3300CC},
                "location":{
                  "x":3,
                  "y":450},
                "size":{
                  "width":40,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"45"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1<br> (If &quot;[[LVAR1.x]]&quot; 等于 &quot;20&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"stringLiteral",
                      "value":"[[LVAR1.x]]",
                      "localVariables":{
                        "lvar1":{
                          "exprType":"fcall",
                          "functionName":"GetWidget",
                          "arguments":[{
                              "exprType":"pathLiteral",
                              "isThis":false,
                              "isFocused":false,
                              "isTarget":false,
                              "value":["4d05b6231d404ffc9103348e067836a3"]}]}},
                      "stos":[{
                          "computedType":"int",
                          "sto":"propCall",
                          "thisSTO":{
                            "sto":"var",
                            "name":"lvar1"},
                          "prop":"x"}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"20",
                      "stos":[]}},
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 消息显示界面",
                      "target":{
                        "targetType":"page",
                        "url":"消息显示界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]},
{
                  "description":"用例 2<br> (Else If &quot;[[LVAR1.x]]&quot; 等于 &quot;0&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"stringLiteral",
                      "value":"[[LVAR1.x]]",
                      "localVariables":{
                        "lvar1":{
                          "exprType":"fcall",
                          "functionName":"GetWidget",
                          "arguments":[{
                              "exprType":"pathLiteral",
                              "isThis":false,
                              "isFocused":false,
                              "isTarget":false,
                              "value":["724668ab7b0d41a78fe89eba68963368"]}]}},
                      "stos":[{
                          "computedType":"int",
                          "sto":"propCall",
                          "thisSTO":{
                            "sto":"var",
                            "name":"lvar1"},
                          "prop":"x"}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"0",
                      "stos":[]}},
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 成长记录显示 到 (320,72) 线性 100ms",
                      "objectsToMoves":[{
                          "objectPath":["724668ab7b0d41a78fe89eba68963368"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"320",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"72",
                              "stos":[]},
                            "options":{
                              "easing":"linear",
                              "duration":100}}}]},
{
                      "action":"moveWidget",
                      "description":"移动 成长记录首页 到 (20,72) 线性 100ms",
                      "objectsToMoves":[{
                          "objectPath":["4d05b6231d404ffc9103348e067836a3"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"20",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"72",
                              "stos":[]},
                            "options":{
                              "easing":"linear",
                              "duration":100}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/成长记录界面/u76.png"}},
{
          "id":"2048b83e22244bdab2339e8ceb1f7e7a",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"2272022aed904078b3587a8d6f2eb98b"}]}},
  "masters":{
    "2272022aed904078b3587a8d6f2eb98b":{
      "packageId":"2272022aed904078b3587a8d6f2eb98b",
      "type":"Axure:Master",
      "name":"导航-成长",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"52adea5103154934bc78bb79108dd75b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":60}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"acb7f67a923e421cb0fa652276bd5593",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":60}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/消息显示界面/u519.png"}},
{
            "id":"45a030ad283b49b7bbbf95a2043cb3da",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0x7200CCCC},
{
                    "color":0x7200CCCC},
{
                    "color":0x9333CC99},
{
                    "color":0x9333CC99}]},
              "size":{
                "width":320,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0029af95ccf240bea0d932a7fa76955e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0x7200CCCC},
{
                        "color":0x7200CCCC},
{
                        "color":0x9333CC99},
{
                        "color":0x9333CC99}]},
                  "size":{
                    "width":320,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/消息显示界面/u521.png"}},
{
            "id":"68cc1923043b42b48bb8306c7c78479b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xE2333333},
              "location":{
                "x":0,
                "y":20},
              "size":{
                "width":320,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"85aff0bd203a4b52a5f3305b085f6cf3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xE2333333},
                  "location":{
                    "x":0,
                    "y":20},
                  "size":{
                    "width":320,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/消息显示界面/u523.png"}},
{
            "id":"a414965c5559460ca30c0637a240b4bd",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"36px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":22,
                "y":20},
              "size":{
                "width":21,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"70eca443d7e5495a88a24d2c6cb2db2d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"36px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":22,
                    "y":20},
                  "size":{
                    "width":21,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ae55a06c4cf3402ead48071c921ae2e6",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":60,
                "y":30},
              "size":{
                "width":37,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6a032cad01be4d518600bbd94ca140ee",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":60,
                    "y":30},
                  "size":{
                    "width":37,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ea29d0e6c714403da18d3c74b946b212",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":45,
                "y":31},
              "size":{
                "width":10,
                "height":20},
              "borderWidth":"2",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF333333}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/消息显示界面/u529_line.png"}},
{
            "id":"a02bf82396214eecbb6fd8a7feca06cb",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":298,
                "y":30},
              "size":{
                "width":3,
                "height":3},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"928d08372a564047b1684c05f6c60d57",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":298,
                    "y":30},
                  "size":{
                    "width":3,
                    "height":3},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/消息显示界面/u530.png"}},
{
            "id":"f907ef5947d6412aaf0dad43ba18f7c9",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":298,
                "y":38},
              "size":{
                "width":3,
                "height":3},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3290c765af5f474288a8fa0044c91183",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":298,
                    "y":38},
                  "size":{
                    "width":3,
                    "height":3},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/消息显示界面/u530.png"}},
{
            "id":"ab2cd1ceb58b47fca05fd28cee44d906",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":298,
                "y":46},
              "size":{
                "width":3,
                "height":3},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4e4410039e864d75965ce500fc047463",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":298,
                    "y":46},
                  "size":{
                    "width":3,
                    "height":3},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/消息显示界面/u530.png"}},
{
            "id":"bf7d9160a4274aa088b36c9fadd69c9a",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":22,
                "y":30},
              "size":{
                "width":20,
                "height":20}},
            "adaptiveStyles":{
}},
{
            "id":"8c1b6f6985124cb1bf9e46cec02f9338",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":289,
                "y":25},
              "size":{
                "width":20,
                "height":30}},
            "adaptiveStyles":{
}}]}}},
  "objectPaths":{
    "4d41da32b319455dae7db058f0eb0839":{
      "scriptId":"u0"},
    "fcaf5b795308440badeeb1628862979b":{
      "scriptId":"u1"},
    "4d05b6231d404ffc9103348e067836a3":{
      "scriptId":"u2"},
    "7f93741887994f718838687bba603bbb":{
      "scriptId":"u3"},
    "02484748acb546699c7e8579fab5ffa7":{
      "scriptId":"u4"},
    "fb23de988ad142c48a16ae574b9e86dc":{
      "scriptId":"u5"},
    "0635761146964e9fa6c63d3b20481ce2":{
      "scriptId":"u6"},
    "ba207fbbf0f04303bffdb4a93f85124a":{
      "scriptId":"u7"},
    "734ec7064fab45e8bd26864464d34464":{
      "scriptId":"u8"},
    "ee777f6203484c5095d71bc8ee71fd25":{
      "scriptId":"u9"},
    "10368720610941e9abe62dce1e5db0b1":{
      "scriptId":"u10"},
    "bfb9671209b34e50a41fec7d664332fd":{
      "scriptId":"u11"},
    "54acbe81952d48839c2a66f08586063f":{
      "scriptId":"u12"},
    "f43b0981396b4d7290e1778f82bc2099":{
      "scriptId":"u13"},
    "6f4a89a9ac7c44a383697014a616feb4":{
      "scriptId":"u14"},
    "724668ab7b0d41a78fe89eba68963368":{
      "scriptId":"u15"},
    "746742b835494555b9cae80a369e32b2":{
      "scriptId":"u16"},
    "0e494d1b216e451796a0b857e2bbd542":{
      "scriptId":"u17"},
    "b6c3d4b7261e45e4a382f825479ba713":{
      "scriptId":"u18"},
    "a5a8b93e36914d0d906c4ddd200fb18b":{
      "scriptId":"u19"},
    "0da37ab9f68041f7ac1e584604d12e33":{
      "scriptId":"u20"},
    "64c47a347f1d49c28a1e933d25fec069":{
      "scriptId":"u21"},
    "d85ab60f70314629ae3ffaf7f6ef7169":{
      "scriptId":"u22"},
    "dff25ed76108456498ba474261d723b0":{
      "scriptId":"u23"},
    "e36d830ac4e944a2ae4a3f62e18e79a5":{
      "scriptId":"u24"},
    "421a30db54af4f91b3c80d1d81418556":{
      "scriptId":"u25"},
    "b6dc205f5f4a477f9ad22d0c99d2d5d3":{
      "scriptId":"u26"},
    "d724531afbbf48999847fe497fcc197b":{
      "scriptId":"u27"},
    "845b632938264218a65bf638ff493b42":{
      "scriptId":"u28"},
    "afb94abbfa1a4e7b88265a3b05a0aa4f":{
      "scriptId":"u29"},
    "2d5b812ca0cb42059e78f94dbe2067e8":{
      "scriptId":"u30"},
    "f70d362e6fc2485db75bc27181d0034a":{
      "scriptId":"u31"},
    "7f1979a72a32434699cd6c5d1b4bbb7a":{
      "scriptId":"u32"},
    "4cb60145e9af4a7c9d20d13dfbf7eb18":{
      "scriptId":"u33"},
    "9a38dd0dbd654ab2887842f8d2606ffa":{
      "scriptId":"u34"},
    "53030e409e734c2aa536412bc9f0be21":{
      "scriptId":"u35"},
    "0634211cf01640ee9d30a023030d4511":{
      "scriptId":"u36"},
    "e1667c0d37e94f7eae650bfa90ac7bb9":{
      "scriptId":"u37"},
    "1229505a58eb4cedbb0cf0457062c1ba":{
      "scriptId":"u38"},
    "68d754eb5d054556a86ecb36b5563a59":{
      "scriptId":"u39"},
    "9a54c15f4b424c9da1c4a3d5d53c2349":{
      "scriptId":"u40"},
    "df803256621e40a1a708ae4902e313d4":{
      "scriptId":"u41"},
    "3f17abb4bce647e58a4d48e4f094aafd":{
      "scriptId":"u42"},
    "a16b1a5357b5435a9e84b131d184dfcb":{
      "scriptId":"u43"},
    "e7d1831bc07b444c9d635e4602402858":{
      "scriptId":"u44"},
    "9dd01143a6544949adcc19ac17830f0f":{
      "scriptId":"u45"},
    "2648191a1b294952b94ba879a53d9740":{
      "scriptId":"u46"},
    "2a9824f1376b42bfa7b2fcf21dd01687":{
      "scriptId":"u47"},
    "8d3fd0c95db54a10bbf60cfb52ac1bf1":{
      "scriptId":"u48"},
    "2c13e07174664ea491ff65c249250f3d":{
      "scriptId":"u49"},
    "f9e3667bf7fe4c19b02da807a9561497":{
      "scriptId":"u50"},
    "f1bcd706320048c4904b68b7c60d6aa4":{
      "scriptId":"u51"},
    "b06ab4b389b546559d8936efbc67123d":{
      "scriptId":"u52"},
    "5a2f7f7364d94846856be36646f40975":{
      "scriptId":"u53"},
    "557771df579044c095b53ec76fe34569":{
      "scriptId":"u54"},
    "73455d8375584d6bac1cab4ca8a93909":{
      "scriptId":"u55"},
    "533df41d988d4164a2911fb8e5320fad":{
      "scriptId":"u56"},
    "ab5f4c86c45d451ea9b4622094445e23":{
      "scriptId":"u57"},
    "de6164f0d1714bccae1009d1ab35b414":{
      "scriptId":"u58"},
    "54f4ac1bc1ba499891d007049b27857a":{
      "scriptId":"u59"},
    "d569acc732394cb9a5831e6d6430a0c6":{
      "scriptId":"u60"},
    "a98c0167e9e14505a95dd52fe83d737a":{
      "scriptId":"u61"},
    "bc3fd3696dd74d5fbd3ac8b6629d5781":{
      "scriptId":"u62"},
    "292f8d1fec6f474e8faff0ca4842782e":{
      "scriptId":"u63"},
    "e449a0a6a3ec494b9dd6ad1d568dcea3":{
      "scriptId":"u64"},
    "a0c2175c70e748e1866475e6bdf3e254":{
      "scriptId":"u65"},
    "4ee29671ca84488883155a1cae394cd9":{
      "scriptId":"u66"},
    "c0430f0bbca345bbb6ce3f1e476f5a61":{
      "scriptId":"u67"},
    "615d2720ca094d338463cd97d5213e6e":{
      "scriptId":"u68"},
    "a654ce4ec20a4c2ea36ee4b01540c8a1":{
      "scriptId":"u69"},
    "0ecf31d5bf8942d7a7ecb4f54960f98d":{
      "scriptId":"u70"},
    "b54d24a852de4748b46be37a58618d74":{
      "scriptId":"u71"},
    "dbdb862748de45f68d004a3680425ea8":{
      "scriptId":"u72"},
    "0747ce09b3f945d5a219f23ea4606a34":{
      "scriptId":"u73"},
    "5a9a219d5cff45389f0b81b74e71a304":{
      "scriptId":"u74"},
    "7c356060ea294eeeb6fae6edf0e22968":{
      "scriptId":"u75"},
    "a36f97e992f74076a69282e6c8626cf6":{
      "scriptId":"u76"},
    "6f98eeda7eb44bae8a74d83895ab1c84":{
      "scriptId":"u77"},
    "2048b83e22244bdab2339e8ceb1f7e7a":{
      "scriptId":"u78",
      "52adea5103154934bc78bb79108dd75b":{
        "scriptId":"u79"},
      "acb7f67a923e421cb0fa652276bd5593":{
        "scriptId":"u80"},
      "45a030ad283b49b7bbbf95a2043cb3da":{
        "scriptId":"u81"},
      "0029af95ccf240bea0d932a7fa76955e":{
        "scriptId":"u82"},
      "68cc1923043b42b48bb8306c7c78479b":{
        "scriptId":"u83"},
      "85aff0bd203a4b52a5f3305b085f6cf3":{
        "scriptId":"u84"},
      "a414965c5559460ca30c0637a240b4bd":{
        "scriptId":"u85"},
      "70eca443d7e5495a88a24d2c6cb2db2d":{
        "scriptId":"u86"},
      "ae55a06c4cf3402ead48071c921ae2e6":{
        "scriptId":"u87"},
      "6a032cad01be4d518600bbd94ca140ee":{
        "scriptId":"u88"},
      "ea29d0e6c714403da18d3c74b946b212":{
        "scriptId":"u89"},
      "a02bf82396214eecbb6fd8a7feca06cb":{
        "scriptId":"u90"},
      "928d08372a564047b1684c05f6c60d57":{
        "scriptId":"u91"},
      "f907ef5947d6412aaf0dad43ba18f7c9":{
        "scriptId":"u92"},
      "3290c765af5f474288a8fa0044c91183":{
        "scriptId":"u93"},
      "ab2cd1ceb58b47fca05fd28cee44d906":{
        "scriptId":"u94"},
      "4e4410039e864d75965ce500fc047463":{
        "scriptId":"u95"},
      "bf7d9160a4274aa088b36c9fadd69c9a":{
        "scriptId":"u96"},
      "8c1b6f6985124cb1bf9e46cec02f9338":{
        "scriptId":"u97"}}}});