$axure.loadCurrentPage({
  "url":"消息显示.html",
  "generationDate":new Date(1426661054319.64),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"value"],
  "page":{
    "packageId":"6c4f4689ee844989937d0626c2502bf4",
    "type":"Axure:Page",
    "name":"消息显示",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"dfed9994a71e450eb06f3476a6e75569",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":10},
            "size":{
              "width":320,
              "height":569}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2850677a33074a91b0c2205cb947a2d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":560,
                  "y":10},
                "size":{
                  "width":320,
                  "height":569}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息显示界面/u0.png"}},
{
          "id":"cbc4109e7a9245b7a5b7dd3a2f3d6828",
          "label":"通知类消息",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":70},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"bcdce6b99ed04ae4909b0832504649a4",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"7d2ae3b27233491a9ae7f20ddb6c2a16",
                  "label":"背景",
                  "parentDynamicPanel":"cbc4109e7a9245b7a5b7dd3a2f3d6828",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":280,
                      "height":220},
                    "cornerRadiusTopLeft":"6"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f9d3c3101eb249b6bab3154360ad078b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"cbc4109e7a9245b7a5b7dd3a2f3d6828",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":280,
                          "height":220},
                        "cornerRadiusTopLeft":"6"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/消息显示界面/背景_u4.png"}},
{
                  "id":"a26fe965156647babaebb7fae1eb4684",
                  "label":"",
                  "parentDynamicPanel":"cbc4109e7a9245b7a5b7dd3a2f3d6828",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":30},
                    "size":{
                      "width":260,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF777777}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/消息显示界面/u6_line.png"}},
{
                  "id":"926a52428b0e4a4da4105e1f6a8f6d6b",
                  "label":"标题",
                  "parentDynamicPanel":"cbc4109e7a9245b7a5b7dd3a2f3d6828",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0033CC,
                      "opacity":1},
                    "location":{
                      "x":10,
                      "y":11},
                    "size":{
                      "width":144,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cf02fbb49dc146c6b4a9055c728806a6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"cbc4109e7a9245b7a5b7dd3a2f3d6828",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Bold', '微软雅黑'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0033CC,
                          "opacity":1},
                        "location":{
                          "x":10,
                          "y":11},
                        "size":{
                          "width":144,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d0ff714154a44578ba0d350959b0157b",
                  "label":"时间",
                  "parentDynamicPanel":"cbc4109e7a9245b7a5b7dd3a2f3d6828",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"right",
                    "location":{
                      "x":237,
                      "y":11},
                    "size":{
                      "width":33,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"74ffbefe22bd496fa2ac3d34f2551293",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"cbc4109e7a9245b7a5b7dd3a2f3d6828",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"right",
                        "location":{
                          "x":237,
                          "y":11},
                        "size":{
                          "width":33,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f8886270091542beadcc1b4c04230b1b",
                  "label":"内容",
                  "parentDynamicPanel":"cbc4109e7a9245b7a5b7dd3a2f3d6828",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":40},
                    "size":{
                      "width":260,
                      "height":96}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d34467b2fe734568a4ec0d20901ef399",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"cbc4109e7a9245b7a5b7dd3a2f3d6828",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":40},
                        "size":{
                          "width":260,
                          "height":96}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1b03b6b9b99e4ef68f630a95ece82f0c",
                  "label":"",
                  "parentDynamicPanel":"cbc4109e7a9245b7a5b7dd3a2f3d6828",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":168},
                    "size":{
                      "width":260,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF777777}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/消息显示界面/u6_line.png"}},
{
                  "id":"7005694d633d4686acc89f929788f6b0",
                  "label":"落款",
                  "parentDynamicPanel":"cbc4109e7a9245b7a5b7dd3a2f3d6828",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":152,
                      "y":146},
                    "size":{
                      "width":118,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"55a50ade2ba54988833aba944acaedce",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"cbc4109e7a9245b7a5b7dd3a2f3d6828",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":152,
                          "y":146},
                        "size":{
                          "width":118,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b3d312039b8e447fad852eaa708175f2",
                  "label":"确认按钮",
                  "parentDynamicPanel":"cbc4109e7a9245b7a5b7dd3a2f3d6828",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
}},
                    "location":{
                      "x":230,
                      "y":180},
                    "size":{
                      "width":30,
                      "height":30},
                    "cornerRadiusTopLeft":"12"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b93dea62c1a5400d8b0f52020f5de9d5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"cbc4109e7a9245b7a5b7dd3a2f3d6828",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
}},
                        "location":{
                          "x":230,
                          "y":180},
                        "size":{
                          "width":30,
                          "height":30},
                        "cornerRadiusTopLeft":"12"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 被选中的 确认按钮 = &quot;toggle&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["b3d312039b8e447fad852eaa708175f2"]},
{
                                        "exprType":"stringLiteral",
                                        "value":"toggle",
                                        "stos":[]}]}]}},
{
                              "action":"fadeWidget",
                              "description":"切换 确认提示",
                              "objectsToFades":[{
                                  "objectPath":["e5d783443f174f79b23c1412b7ef71d3"],
                                  "fadeInfo":{
                                    "fadeType":"toggle",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/消息显示界面/确认按钮_u16.png",
                    "selected~":"images/消息显示界面/确认按钮_u16_selected.png"}},
{
                  "id":"e5d783443f174f79b23c1412b7ef71d3",
                  "label":"确认提示",
                  "parentDynamicPanel":"cbc4109e7a9245b7a5b7dd3a2f3d6828",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":10,
                      "y":188},
                    "size":{
                      "width":131,
                      "height":16},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5960b025099c4c32ad8ef6d302a84bb7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"cbc4109e7a9245b7a5b7dd3a2f3d6828",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "location":{
                          "x":10,
                          "y":188},
                        "size":{
                          "width":131,
                          "height":16},
                        "visible":false},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"8c5e6d1a140d4b1baef478fff7d24b9d",
          "label":"问卷类消息",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":600},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"3352230193c54f1585267f7a377419cd",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"02b42bc94971437aadd7785b581fe76b",
                  "label":"背景",
                  "parentDynamicPanel":"8c5e6d1a140d4b1baef478fff7d24b9d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":280,
                      "height":200},
                    "cornerRadiusTopLeft":"6"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7d11dd405c02445cb459c52cde638b53",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8c5e6d1a140d4b1baef478fff7d24b9d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":280,
                          "height":200},
                        "cornerRadiusTopLeft":"6"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/消息显示界面/背景_u21.png"}},
{
                  "id":"f88b55c9b4c44ac1b8ca2e5593811c52",
                  "label":"",
                  "parentDynamicPanel":"8c5e6d1a140d4b1baef478fff7d24b9d",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":30},
                    "size":{
                      "width":260,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF777777}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/消息显示界面/u6_line.png"}},
{
                  "id":"5b86fda4e6184e6282f0efab437fd8b7",
                  "label":"标题",
                  "parentDynamicPanel":"8c5e6d1a140d4b1baef478fff7d24b9d",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0033CC,
                      "opacity":1},
                    "location":{
                      "x":10,
                      "y":11},
                    "size":{
                      "width":209,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8341762237f8471abdfb510e92c58d1b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8c5e6d1a140d4b1baef478fff7d24b9d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Bold', '微软雅黑'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0033CC,
                          "opacity":1},
                        "location":{
                          "x":10,
                          "y":11},
                        "size":{
                          "width":209,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"407935ea8da14e2b9414cc98d1e335f8",
                  "label":"时间",
                  "parentDynamicPanel":"8c5e6d1a140d4b1baef478fff7d24b9d",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"right",
                    "location":{
                      "x":243,
                      "y":12},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4b425b3dbcc54bbb8c0b8a971a0c8837",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8c5e6d1a140d4b1baef478fff7d24b9d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"right",
                        "location":{
                          "x":243,
                          "y":12},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b1a5a6cf1215497698b593f96b6af7f5",
                  "label":"内容",
                  "parentDynamicPanel":"8c5e6d1a140d4b1baef478fff7d24b9d",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":40},
                    "size":{
                      "width":260,
                      "height":64}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6632d2c188d24808963d1a71a3c5a647",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8c5e6d1a140d4b1baef478fff7d24b9d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":40},
                        "size":{
                          "width":260,
                          "height":64}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8a44ccec08254794985d45b485ed6368",
                  "label":"",
                  "parentDynamicPanel":"8c5e6d1a140d4b1baef478fff7d24b9d",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":135},
                    "size":{
                      "width":260,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF777777}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/消息显示界面/u6_line.png"}},
{
                  "id":"ae435fc051904b8d9f9e90a1f36eeb7d",
                  "label":"落款",
                  "parentDynamicPanel":"8c5e6d1a140d4b1baef478fff7d24b9d",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":152,
                      "y":114},
                    "size":{
                      "width":118,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e4d6aa896ee4487bb6bebd67ff7379f1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8c5e6d1a140d4b1baef478fff7d24b9d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":152,
                          "y":114},
                        "size":{
                          "width":118,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"168618eb98c04eef8c24f06435c46a56",
                  "label":"打勾",
                  "parentDynamicPanel":"8c5e6d1a140d4b1baef478fff7d24b9d",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
}},
                    "location":{
                      "x":145,
                      "y":155},
                    "size":{
                      "width":25,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bd848a84048b4449b6fe5b5ff106bb8d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8c5e6d1a140d4b1baef478fff7d24b9d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
}},
                        "location":{
                          "x":145,
                          "y":155},
                        "size":{
                          "width":25,
                          "height":25}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 被选中的 打勾 = &quot;true&quot;, 与<br> 被选中的 打叉 = &quot;false&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["168618eb98c04eef8c24f06435c46a56"]},
{
                                        "exprType":"stringLiteral",
                                        "value":"true",
                                        "stos":[]}]},
{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["dc25b21df34849a4a2bfef5a7b7f77ae"]},
{
                                        "exprType":"stringLiteral",
                                        "value":"false",
                                        "stos":[]}]}]}},
{
                              "action":"setFunction",
                              "description":"设置 文字于 选择提示 = &quot;您已选择了√&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetWidgetRichText",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["5108ab7a71a3466dba75a7478050d7bd"]},
{
                                        "exprType":"stringLiteral",
                                        "value":"您已选择了√",
                                        "stos":[]},
{
                                        "exprType":"booleanLiteral",
                                        "value":true}]}]}},
{
                              "action":"fadeWidget",
                              "description":"显示 选择提示,<br>打勾数,<br>打叉数",
                              "objectsToFades":[{
                                  "objectPath":["8635a24f803e406ba5eac0620c34e6ee"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["39aa5fa567d445b3b9bca8dfef5dd833"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["50aaf4d9e227411db079c42ec692e915"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/消息显示界面/打勾_u33.png",
                    "selected~":"images/消息显示界面/打勾_u33_selected.png"}},
{
                  "id":"dc25b21df34849a4a2bfef5a7b7f77ae",
                  "label":"打叉",
                  "parentDynamicPanel":"8c5e6d1a140d4b1baef478fff7d24b9d",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
}},
                    "location":{
                      "x":219,
                      "y":155},
                    "size":{
                      "width":25,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"10402e1877594d30ac76db1f6f46085c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8c5e6d1a140d4b1baef478fff7d24b9d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
}},
                        "location":{
                          "x":219,
                          "y":155},
                        "size":{
                          "width":25,
                          "height":25}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 选中",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[]}},
{
                              "action":"setFunction",
                              "description":"设置 被选中的 打勾 = &quot;false&quot;, 与<br> 被选中的 打叉 = &quot;true&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["168618eb98c04eef8c24f06435c46a56"]},
{
                                        "exprType":"stringLiteral",
                                        "value":"false",
                                        "stos":[]}]},
{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["dc25b21df34849a4a2bfef5a7b7f77ae"]},
{
                                        "exprType":"stringLiteral",
                                        "value":"true",
                                        "stos":[]}]}]}},
{
                              "action":"setFunction",
                              "description":"设置 文字于 选择提示 = &quot;您已选择了×&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetWidgetRichText",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["5108ab7a71a3466dba75a7478050d7bd"]},
{
                                        "exprType":"stringLiteral",
                                        "value":"您已选择了×",
                                        "stos":[]},
{
                                        "exprType":"booleanLiteral",
                                        "value":true}]}]}},
{
                              "action":"fadeWidget",
                              "description":"显示 选择提示,<br>打勾数,<br>打叉数",
                              "objectsToFades":[{
                                  "objectPath":["8635a24f803e406ba5eac0620c34e6ee"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["39aa5fa567d445b3b9bca8dfef5dd833"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["50aaf4d9e227411db079c42ec692e915"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/消息显示界面/打叉_u35.png",
                    "selected~":"images/消息显示界面/打叉_u35_selected.png"}},
{
                  "id":"8635a24f803e406ba5eac0620c34e6ee",
                  "label":"选择提示",
                  "parentDynamicPanel":"8c5e6d1a140d4b1baef478fff7d24b9d",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":10,
                      "y":160},
                    "size":{
                      "width":74,
                      "height":16},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5108ab7a71a3466dba75a7478050d7bd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8c5e6d1a140d4b1baef478fff7d24b9d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "location":{
                          "x":10,
                          "y":160},
                        "size":{
                          "width":74,
                          "height":16},
                        "visible":false},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"39aa5fa567d445b3b9bca8dfef5dd833",
                  "label":"打勾数",
                  "parentDynamicPanel":"8c5e6d1a140d4b1baef478fff7d24b9d",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":false,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":173,
                      "y":158},
                    "size":{
                      "width":19,
                      "height":19},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e390489f32d74e3b84700202265d5611",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8c5e6d1a140d4b1baef478fff7d24b9d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":173,
                          "y":158},
                        "size":{
                          "width":19,
                          "height":19},
                        "visible":false},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"50aaf4d9e227411db079c42ec692e915",
                  "label":"打叉数",
                  "parentDynamicPanel":"8c5e6d1a140d4b1baef478fff7d24b9d",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":false,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":245,
                      "y":158},
                    "size":{
                      "width":19,
                      "height":19},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a787c2add8b443ccb76ad9316563ae03",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8c5e6d1a140d4b1baef478fff7d24b9d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":245,
                          "y":158},
                        "size":{
                          "width":19,
                          "height":19},
                        "visible":false},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"4605d6fdbca742459737820bfb10f96c",
          "label":"照片类消息",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":820},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"bbf88941fbdc4c718a0a1e569a44ad8f",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"043d26348458435daae9a68e7ffdcec3",
                  "label":"背景",
                  "parentDynamicPanel":"4605d6fdbca742459737820bfb10f96c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":280,
                      "height":230},
                    "cornerRadiusTopLeft":"6"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8a86236a91c74ce7b4da6509139add1b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4605d6fdbca742459737820bfb10f96c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":280,
                          "height":230},
                        "cornerRadiusTopLeft":"6"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/消息显示界面/背景_u44.png"}},
{
                  "id":"0183834d9f824b9eb1f9e5c6d01dc3b3",
                  "label":"",
                  "parentDynamicPanel":"4605d6fdbca742459737820bfb10f96c",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":30},
                    "size":{
                      "width":260,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF777777}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/消息显示界面/u6_line.png"}},
{
                  "id":"ba53a399d81741cb91ba504406e42e2a",
                  "label":"标题",
                  "parentDynamicPanel":"4605d6fdbca742459737820bfb10f96c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0033CC,
                      "opacity":1},
                    "location":{
                      "x":10,
                      "y":11},
                    "size":{
                      "width":131,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e9370b65ee904ec3a44bfb61f44300be",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4605d6fdbca742459737820bfb10f96c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Bold', '微软雅黑'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0033CC,
                          "opacity":1},
                        "location":{
                          "x":10,
                          "y":11},
                        "size":{
                          "width":131,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"eea47d53ff634a7cbbd9972f98ec7abc",
                  "label":"时间",
                  "parentDynamicPanel":"4605d6fdbca742459737820bfb10f96c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"right",
                    "location":{
                      "x":243,
                      "y":12},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b2c4f276023840e3b5598d14bb7c5b65",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4605d6fdbca742459737820bfb10f96c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"right",
                        "location":{
                          "x":243,
                          "y":12},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1ae88d81a3054c7895230d5c19befadd",
                  "label":"",
                  "parentDynamicPanel":"4605d6fdbca742459737820bfb10f96c",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":180},
                    "size":{
                      "width":260,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF777777}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/消息显示界面/u6_line.png"}},
{
                  "id":"95caf53dfb48443aa0775d255f3251be",
                  "label":"落款",
                  "parentDynamicPanel":"4605d6fdbca742459737820bfb10f96c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":152,
                      "y":154},
                    "size":{
                      "width":118,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ea69fc23752e409199c041432a1911ba",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4605d6fdbca742459737820bfb10f96c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":152,
                          "y":154},
                        "size":{
                          "width":118,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"84a44cb325fb46cb95894691ae06b26b",
                  "label":"照片",
                  "parentDynamicPanel":"4605d6fdbca742459737820bfb10f96c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":50},
                    "size":{
                      "width":120,
                      "height":84}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"64209d1fd38d4c43a5e1274e2c0dac66",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4605d6fdbca742459737820bfb10f96c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":50},
                        "size":{
                          "width":120,
                          "height":84}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/消息显示界面/照片_u54.png"}},
{
                  "id":"81e9e6fdec5e4d92806091c9de49f62c",
                  "label":"照片",
                  "parentDynamicPanel":"4605d6fdbca742459737820bfb10f96c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":140,
                      "y":50},
                    "size":{
                      "width":120,
                      "height":84}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"474dd0eedc3641b1a627d0ec858ebbea",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4605d6fdbca742459737820bfb10f96c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":140,
                          "y":50},
                        "size":{
                          "width":120,
                          "height":84}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/消息显示界面/照片_u56.png"}},
{
                  "id":"8d1d2b6cc0f24ece9edc443c07c200f7",
                  "label":"点赞图标",
                  "parentDynamicPanel":"4605d6fdbca742459737820bfb10f96c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
}},
                    "location":{
                      "x":10,
                      "y":192},
                    "size":{
                      "width":33,
                      "height":30},
                    "cornerRadiusTopLeft":"16"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"30997cd8f14a4e80943cd61a28b6855f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4605d6fdbca742459737820bfb10f96c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
}},
                        "location":{
                          "x":10,
                          "y":192},
                        "size":{
                          "width":33,
                          "height":30},
                        "cornerRadiusTopLeft":"16"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1<br> (If 被选中的 This 等于 假)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":"==",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetCheckState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":true,
                                  "isFocused":false,
                                  "isTarget":false}]},
                            "rightExpr":{
                              "exprType":"booleanLiteral",
                              "value":false}},
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 被选中的 点赞图标 = &quot;true&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["8d1d2b6cc0f24ece9edc443c07c200f7"]},
{
                                        "exprType":"stringLiteral",
                                        "value":"true",
                                        "stos":[]}]}]}},
{
                              "action":"setFunction",
                              "description":"设置 文字于 点赞数 = &quot;[[LVAR1+1]]&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetWidgetRichText",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["2278b3897aed482b86c42b7cfe316641"]},
{
                                        "exprType":"stringLiteral",
                                        "value":"[[LVAR1+1]]",
                                        "localVariables":{
                                          "lvar1":{
                                            "exprType":"fcall",
                                            "functionName":"GetWidgetText",
                                            "arguments":[{
                                                "exprType":"pathLiteral",
                                                "isThis":false,
                                                "isFocused":false,
                                                "isTarget":false,
                                                "value":["76029b1908b1494a9b2151ef0a00ed1f"]}]}},
                                        "stos":[{
                                            "computedType":"int",
                                            "sto":"binOp",
                                            "op":"+",
                                            "leftSTO":{
                                              "sto":"var",
                                              "name":"lvar1"},
                                            "rightSTO":{
                                              "computedType":"int",
                                              "sto":"literal",
                                              "value":1}}]},
{
                                        "exprType":"booleanLiteral",
                                        "value":true}]}]}}]},
{
                          "description":"用例 1<br> (Else If 被选中的 This 等于 真)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":"==",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetCheckState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":true,
                                  "isFocused":false,
                                  "isTarget":false}]},
                            "rightExpr":{
                              "exprType":"booleanLiteral",
                              "value":true}},
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 被选中的 点赞图标 = &quot;false&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["8d1d2b6cc0f24ece9edc443c07c200f7"]},
{
                                        "exprType":"stringLiteral",
                                        "value":"false",
                                        "stos":[]}]}]}},
{
                              "action":"setFunction",
                              "description":"设置 文字于 点赞数 = &quot;[[LVAR1-1]]&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetWidgetRichText",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["2278b3897aed482b86c42b7cfe316641"]},
{
                                        "exprType":"stringLiteral",
                                        "value":"[[LVAR1-1]]",
                                        "localVariables":{
                                          "lvar1":{
                                            "exprType":"fcall",
                                            "functionName":"GetWidgetText",
                                            "arguments":[{
                                                "exprType":"pathLiteral",
                                                "isThis":false,
                                                "isFocused":false,
                                                "isTarget":false,
                                                "value":["76029b1908b1494a9b2151ef0a00ed1f"]}]}},
                                        "stos":[{
                                            "computedType":"int",
                                            "sto":"binOp",
                                            "op":"-",
                                            "leftSTO":{
                                              "sto":"var",
                                              "name":"lvar1"},
                                            "rightSTO":{
                                              "computedType":"int",
                                              "sto":"literal",
                                              "value":1}}]},
{
                                        "exprType":"booleanLiteral",
                                        "value":true}]}]}}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/消息显示界面/点赞图标_u58.png",
                    "selected~":"images/消息显示界面/点赞图标_u58_selected.png"}},
{
                  "id":"76029b1908b1494a9b2151ef0a00ed1f",
                  "label":"点赞数",
                  "parentDynamicPanel":"4605d6fdbca742459737820bfb10f96c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":53,
                      "y":198},
                    "size":{
                      "width":19,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2278b3897aed482b86c42b7cfe316641",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4605d6fdbca742459737820bfb10f96c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":53,
                          "y":198},
                        "size":{
                          "width":19,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"1189f3de9527464983126981abc8d89e",
          "label":"课表类消息",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":310},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"c965f8f0c2aa4358a1dab6cf62df266d",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"be2a9d38326e489392e8c8fa60322542",
                  "label":"背景",
                  "parentDynamicPanel":"1189f3de9527464983126981abc8d89e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":280,
                      "height":180},
                    "cornerRadiusTopLeft":"6"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bcce7eac3e584c6f909efc995a4c3dcd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1189f3de9527464983126981abc8d89e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":280,
                          "height":180},
                        "cornerRadiusTopLeft":"6"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/消息显示界面/背景_u63.png"}},
{
                  "id":"4c72e12b5b1f4981adbd5ddd0a2800af",
                  "label":"",
                  "parentDynamicPanel":"1189f3de9527464983126981abc8d89e",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":30},
                    "size":{
                      "width":260,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF777777}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/消息显示界面/u6_line.png"}},
{
                  "id":"cea9f84cf4c24d7a9396f44c9ebadac6",
                  "label":"标题",
                  "parentDynamicPanel":"1189f3de9527464983126981abc8d89e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0033CC,
                      "opacity":1},
                    "location":{
                      "x":10,
                      "y":11},
                    "size":{
                      "width":53,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"15c05098ba4f483bad9d9a255c499dbe",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1189f3de9527464983126981abc8d89e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Bold', '微软雅黑'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0033CC,
                          "opacity":1},
                        "location":{
                          "x":10,
                          "y":11},
                        "size":{
                          "width":53,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"adcd3c9daa214401b0a0c7dadc3c1997",
                  "label":"时间",
                  "parentDynamicPanel":"1189f3de9527464983126981abc8d89e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"right",
                    "location":{
                      "x":244,
                      "y":11},
                    "size":{
                      "width":26,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"81b109949298487ab8c4d1821a3556a8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1189f3de9527464983126981abc8d89e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"right",
                        "location":{
                          "x":244,
                          "y":11},
                        "size":{
                          "width":26,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8fc612ca820c43f6a88f3d4ca704d653",
                  "label":"内容",
                  "parentDynamicPanel":"1189f3de9527464983126981abc8d89e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":126,
                      "y":40},
                    "size":{
                      "width":130,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3b7ba05111c64ddb92f73837eb8df8ef",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1189f3de9527464983126981abc8d89e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":126,
                          "y":40},
                        "size":{
                          "width":130,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"65ef90c14629448890f5f60bbfd45eba",
                  "label":"落款",
                  "parentDynamicPanel":"1189f3de9527464983126981abc8d89e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":152,
                      "y":151},
                    "size":{
                      "width":118,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7d24272c64b84a7f8b525fba5dcff56c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1189f3de9527464983126981abc8d89e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":152,
                          "y":151},
                        "size":{
                          "width":118,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"cb2022e0e84d46dea84bf74b62b2701f",
                  "label":"",
                  "parentDynamicPanel":"1189f3de9527464983126981abc8d89e",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":40},
                    "size":{
                      "width":106,
                      "height":101}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3df9865b8e424d5899215334936c187b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1189f3de9527464983126981abc8d89e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":40},
                        "size":{
                          "width":106,
                          "height":101}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/消息显示界面/u74.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "dfed9994a71e450eb06f3476a6e75569":{
      "scriptId":"u0"},
    "2850677a33074a91b0c2205cb947a2d1":{
      "scriptId":"u1"},
    "cbc4109e7a9245b7a5b7dd3a2f3d6828":{
      "scriptId":"u2"},
    "7d2ae3b27233491a9ae7f20ddb6c2a16":{
      "scriptId":"u3"},
    "f9d3c3101eb249b6bab3154360ad078b":{
      "scriptId":"u4"},
    "a26fe965156647babaebb7fae1eb4684":{
      "scriptId":"u5"},
    "926a52428b0e4a4da4105e1f6a8f6d6b":{
      "scriptId":"u6"},
    "cf02fbb49dc146c6b4a9055c728806a6":{
      "scriptId":"u7"},
    "d0ff714154a44578ba0d350959b0157b":{
      "scriptId":"u8"},
    "74ffbefe22bd496fa2ac3d34f2551293":{
      "scriptId":"u9"},
    "f8886270091542beadcc1b4c04230b1b":{
      "scriptId":"u10"},
    "d34467b2fe734568a4ec0d20901ef399":{
      "scriptId":"u11"},
    "1b03b6b9b99e4ef68f630a95ece82f0c":{
      "scriptId":"u12"},
    "7005694d633d4686acc89f929788f6b0":{
      "scriptId":"u13"},
    "55a50ade2ba54988833aba944acaedce":{
      "scriptId":"u14"},
    "b3d312039b8e447fad852eaa708175f2":{
      "scriptId":"u15"},
    "b93dea62c1a5400d8b0f52020f5de9d5":{
      "scriptId":"u16"},
    "e5d783443f174f79b23c1412b7ef71d3":{
      "scriptId":"u17"},
    "5960b025099c4c32ad8ef6d302a84bb7":{
      "scriptId":"u18"},
    "8c5e6d1a140d4b1baef478fff7d24b9d":{
      "scriptId":"u19"},
    "02b42bc94971437aadd7785b581fe76b":{
      "scriptId":"u20"},
    "7d11dd405c02445cb459c52cde638b53":{
      "scriptId":"u21"},
    "f88b55c9b4c44ac1b8ca2e5593811c52":{
      "scriptId":"u22"},
    "5b86fda4e6184e6282f0efab437fd8b7":{
      "scriptId":"u23"},
    "8341762237f8471abdfb510e92c58d1b":{
      "scriptId":"u24"},
    "407935ea8da14e2b9414cc98d1e335f8":{
      "scriptId":"u25"},
    "4b425b3dbcc54bbb8c0b8a971a0c8837":{
      "scriptId":"u26"},
    "b1a5a6cf1215497698b593f96b6af7f5":{
      "scriptId":"u27"},
    "6632d2c188d24808963d1a71a3c5a647":{
      "scriptId":"u28"},
    "8a44ccec08254794985d45b485ed6368":{
      "scriptId":"u29"},
    "ae435fc051904b8d9f9e90a1f36eeb7d":{
      "scriptId":"u30"},
    "e4d6aa896ee4487bb6bebd67ff7379f1":{
      "scriptId":"u31"},
    "168618eb98c04eef8c24f06435c46a56":{
      "scriptId":"u32"},
    "bd848a84048b4449b6fe5b5ff106bb8d":{
      "scriptId":"u33"},
    "dc25b21df34849a4a2bfef5a7b7f77ae":{
      "scriptId":"u34"},
    "10402e1877594d30ac76db1f6f46085c":{
      "scriptId":"u35"},
    "8635a24f803e406ba5eac0620c34e6ee":{
      "scriptId":"u36"},
    "5108ab7a71a3466dba75a7478050d7bd":{
      "scriptId":"u37"},
    "39aa5fa567d445b3b9bca8dfef5dd833":{
      "scriptId":"u38"},
    "e390489f32d74e3b84700202265d5611":{
      "scriptId":"u39"},
    "50aaf4d9e227411db079c42ec692e915":{
      "scriptId":"u40"},
    "a787c2add8b443ccb76ad9316563ae03":{
      "scriptId":"u41"},
    "4605d6fdbca742459737820bfb10f96c":{
      "scriptId":"u42"},
    "043d26348458435daae9a68e7ffdcec3":{
      "scriptId":"u43"},
    "8a86236a91c74ce7b4da6509139add1b":{
      "scriptId":"u44"},
    "0183834d9f824b9eb1f9e5c6d01dc3b3":{
      "scriptId":"u45"},
    "ba53a399d81741cb91ba504406e42e2a":{
      "scriptId":"u46"},
    "e9370b65ee904ec3a44bfb61f44300be":{
      "scriptId":"u47"},
    "eea47d53ff634a7cbbd9972f98ec7abc":{
      "scriptId":"u48"},
    "b2c4f276023840e3b5598d14bb7c5b65":{
      "scriptId":"u49"},
    "1ae88d81a3054c7895230d5c19befadd":{
      "scriptId":"u50"},
    "95caf53dfb48443aa0775d255f3251be":{
      "scriptId":"u51"},
    "ea69fc23752e409199c041432a1911ba":{
      "scriptId":"u52"},
    "84a44cb325fb46cb95894691ae06b26b":{
      "scriptId":"u53"},
    "64209d1fd38d4c43a5e1274e2c0dac66":{
      "scriptId":"u54"},
    "81e9e6fdec5e4d92806091c9de49f62c":{
      "scriptId":"u55"},
    "474dd0eedc3641b1a627d0ec858ebbea":{
      "scriptId":"u56"},
    "8d1d2b6cc0f24ece9edc443c07c200f7":{
      "scriptId":"u57"},
    "30997cd8f14a4e80943cd61a28b6855f":{
      "scriptId":"u58"},
    "76029b1908b1494a9b2151ef0a00ed1f":{
      "scriptId":"u59"},
    "2278b3897aed482b86c42b7cfe316641":{
      "scriptId":"u60"},
    "1189f3de9527464983126981abc8d89e":{
      "scriptId":"u61"},
    "be2a9d38326e489392e8c8fa60322542":{
      "scriptId":"u62"},
    "bcce7eac3e584c6f909efc995a4c3dcd":{
      "scriptId":"u63"},
    "4c72e12b5b1f4981adbd5ddd0a2800af":{
      "scriptId":"u64"},
    "cea9f84cf4c24d7a9396f44c9ebadac6":{
      "scriptId":"u65"},
    "15c05098ba4f483bad9d9a255c499dbe":{
      "scriptId":"u66"},
    "adcd3c9daa214401b0a0c7dadc3c1997":{
      "scriptId":"u67"},
    "81b109949298487ab8c4d1821a3556a8":{
      "scriptId":"u68"},
    "8fc612ca820c43f6a88f3d4ca704d653":{
      "scriptId":"u69"},
    "3b7ba05111c64ddb92f73837eb8df8ef":{
      "scriptId":"u70"},
    "65ef90c14629448890f5f60bbfd45eba":{
      "scriptId":"u71"},
    "7d24272c64b84a7f8b525fba5dcff56c":{
      "scriptId":"u72"},
    "cb2022e0e84d46dea84bf74b62b2701f":{
      "scriptId":"u73"},
    "3df9865b8e424d5899215334936c187b":{
      "scriptId":"u74"}}});